apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: mathieu@ctoutvert.com
    ## For production environement use "https://acme-v02.api.letsencrypt.org/directory" instead
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - http01:
        ingress:
            class: nginx