kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: custom-azure-resizable
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
  kind: Managed
  cachingmode: None
allowVolumeExpansion: true