apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: elasticsearch-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - ctv-tuto-k8s-elasticsearch.secureholiday.com
      secretName: ctv-tuto-k8s-elasticsearch-test-resize-cert
  rules:
    - host: ctv-tuto-k8s-elasticsearch.secureholiday.com
      http:
        paths:
          - path: /
            backend:
              serviceName: elasticsearch
              servicePort: api