apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-cluster
  namespace: elasticsearch-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: elasticsearch
      environement: demo
  template:
    metadata:
      labels:
        application: elasticsearch
        environement: demo
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: cluster.initial_master_nodes
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
      initContainers:
        # To prevent OOM errors.
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        # Increase the max number of open file descriptors. 
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true